// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGvJq04Uk9TpsI12NZistG8cqIMKgbPg',
    appId: '1:583592017377:web:fd208e16c0f64edb9366a0',
    messagingSenderId: '583592017377',
    projectId: 'login01-69072',
    authDomain: 'login01-69072.firebaseapp.com',
    storageBucket: 'login01-69072.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWt8wOzB0NARKg46jOLO56gJZfrTPVKg',
    appId: '1:583592017377:android:40c5623cc6241e499366a0',
    messagingSenderId: '583592017377',
    projectId: 'login01-69072',
    storageBucket: 'login01-69072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUnQJAN-jzswoccn62lUSa-KKKgw39Yc',
    appId: '1:583592017377:ios:794e01d2714a38519366a0',
    messagingSenderId: '583592017377',
    projectId: 'login01-69072',
    storageBucket: 'login01-69072.appspot.com',
    iosClientId: '583592017377-31fll7gklfp7kt61dek5pqj9d6b8l4ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.login01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUnQJAN-jzswoccn62lUSa-KKKgw39Yc',
    appId: '1:583592017377:ios:794e01d2714a38519366a0',
    messagingSenderId: '583592017377',
    projectId: 'login01-69072',
    storageBucket: 'login01-69072.appspot.com',
    iosClientId: '583592017377-31fll7gklfp7kt61dek5pqj9d6b8l4ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.login01',
  );
}
